# Quality Gate Decision - Story 2.10
# Quality Gate Manager Unificado

schema: 1
story: "2.10"
story_title: "Quality Gate Manager Unificado"
gate: PENDING
status_reason: "Story validated and ready for development. Missing quality gate file created."
reviewer: "Pax (PO)"
updated: "2025-11-30T00:00:00Z"

waiver:
  active: false

# Pre-implementation validation
pre_validation:
  story_format: PASS
  acceptance_criteria: PASS
  definition_of_done: PASS
  dependencies_clear: PASS
  estimates_reasonable: PASS
  rollback_plan: PASS

# Required tests (from story smoke tests QGM-01 to QGM-12)
required_tests:
  p0_critical:
    - id: QGM-01
      name: "Layer 1 Pass"
      description: "Layer 1 passes on clean code (exit code 0)"
      status: PENDING

    - id: QGM-02
      name: "Layer 1 Fail"
      description: "Layer 1 fails on lint errors (exit code 1)"
      status: PENDING

    - id: QGM-03
      name: "Layer 2 Pass"
      description: "Layer 2 passes with no CRITICAL issues (exit code 0)"
      status: PENDING

    - id: QGM-04
      name: "Full Pipeline"
      description: "`aios qa run` executes all layers sequentially"
      status: PENDING

  p1_important:
    - id: QGM-05
      name: "Fail Fast"
      description: "Pipeline stops on Layer 1 failure (Layer 2 not run)"
      status: PENDING

    - id: QGM-06
      name: "Layer Specific"
      description: "`--layer=1` runs only Layer 1"
      status: PENDING

    - id: QGM-07
      name: "Status Command"
      description: "`aios qa status` shows current gate state"
      status: PENDING

    - id: QGM-08
      name: "Config Load"
      description: "Reads quality-gate-config.yaml correctly"
      status: PENDING

    - id: QGM-09
      name: "Reports Saved"
      description: "Results saved to .aios/qa-reports/"
      status: PENDING

    - id: QGM-10
      name: "Exit Codes"
      description: "Correct exit codes per result (0=pass, 1=fail)"
      status: PENDING

  p2_nice_to_have:
    - id: QGM-11
      name: "Performance"
      description: "Full pipeline completes in < 2 minutes"
      status: PENDING

    - id: QGM-12
      name: "Verbose Mode"
      description: "--verbose shows detailed output"
      status: PENDING

# Deliverables scope
deliverables:
  files_to_create:
    - ".aios-core/core/quality-gates/quality-gate-manager.js"
    - ".aios-core/core/quality-gates/layer1-precommit.js"
    - ".aios-core/core/quality-gates/layer2-pr-automation.js"
    - ".aios-core/core/quality-gates/layer3-human-review.js"
    - ".aios-core/core/quality-gates/quality-gate-config.yaml"
    - ".aios-core/core/quality-gates/checklist-generator.js"
    - ".aios-core/cli/commands/qa/index.js"
    - ".aios-core/cli/commands/qa/run.js"
    - ".aios-core/cli/commands/qa/status.js"
    - "tests/unit/quality-gate-manager.test.js"
    - "tests/unit/layer1-precommit.test.js"
    - "tests/unit/layer2-pr-automation.test.js"
    - "tests/integration/quality-gate-pipeline.test.js"
  files_to_update:
    - ".aios-core/cli/index.js"

  layer_architecture:
    - name: "Layer 1: Pre-commit"
      checks:
        - lint
        - test
        - typecheck
      behavior: "fail-fast"
    - name: "Layer 2: PR Automation"
      checks:
        - coderabbit
        - quinn_review
      behavior: "escalate on CRITICAL"
    - name: "Layer 3: Human Review"
      checks:
        - checklist_generation
        - reviewer_assignment
        - signoff_tracking
      behavior: "requires human action"

# Risk assessment (pre-implementation)
risk_summary:
  totals:
    critical: 0
    high: 2
    medium: 2
    low: 1
  highest: high
  identified_risks:
    - id: "INTEGRATION-001"
      severity: high
      finding: "CodeRabbit integration requires WSL on Windows"
      mitigation: "Document WSL requirement, provide fallback skip option"
      status: PLANNED

    - id: "COMPLEXITY-001"
      severity: high
      finding: "Multi-layer orchestration is complex (28h estimate)"
      mitigation: "Implement layers incrementally, test each independently"
      status: PLANNED

    - id: "ASYNC-001"
      severity: medium
      finding: "Async orchestration may have race conditions"
      mitigation: "Sequential execution, proper error propagation"
      status: PLANNED

    - id: "CONFIG-001"
      severity: medium
      finding: "Configuration schema needs validation"
      mitigation: "JSON schema validation on config load"
      status: PLANNED

    - id: "PERF-001"
      severity: low
      finding: "Full pipeline may exceed 2min on slow systems"
      mitigation: "Parallel checks where possible, timeout configuration"
      status: PLANNED

  recommendations:
    must_fix: []
    before_start:
      - "Verify CodeRabbit CLI is available (or can be skipped)"
      - "Review existing lint/test/typecheck npm scripts"
      - "Design config schema before implementation"
    during_implementation:
      - "Implement Layer 1 first (most independent)"
      - "Test fail-fast mechanism early (QGM-05)"
      - "Mock external services for unit tests"
    before_completion:
      - "All 12 QGM tests must pass"
      - "Configuration file documented"
      - "Performance benchmark documented"

# Quality scoring (pre-implementation baseline)
quality_score: 91  # Story quality score (format, clarity, completeness)
# Score breakdown:
# - Format compliance: 20/20
# - Acceptance criteria clarity: 19/20
# - Task breakdown: 18/20
# - Risk mitigation: 17/20
# - Documentation: 17/20

# Gate criteria for PASS
pass_criteria:
  - "All P0 tests (QGM-01 to QGM-04) must pass"
  - "All P1 tests (QGM-05 to QGM-10) must pass"
  - "All P2 tests (QGM-11 to QGM-12) should pass (not blocking)"
  - "Fail-fast mechanism working correctly"
  - "Configuration file properly parsed"
  - "CLI commands functional (aios qa run, aios qa status)"
  - "Reports saved to .aios/qa-reports/"

expires: "2025-12-15T00:00:00Z"  # 2 weeks from approval

evidence:
  story_validated: true
  po_approved: true
  dependencies_met:
    - story: "2.2"
      status: "Done"
    - story: "2.3"
      status: "Ready for Review"
    - story: "2.4"
      status: "Done"
    - story: "2.5"
      status: "Done"
  adr_reference: "ADR-002-migration-map.md"
  blocking_stories:
    - "2.16 (Documentation)"

# CodeRabbit Integration
coderabbit_integration:
  enabled: true
  focus_areas:
    primary:
      - "Error handling in orchestration"
      - "Async/await correctness"
      - "Configuration validation"
    secondary:
      - "CLI argument parsing"
      - "Exit code consistency"
      - "Logging quality"
  self_healing:
    primary_agent: "@dev"
    max_iterations: 3
    timeout_minutes: 15
    severity_filter:
      - CRITICAL
      - HIGH

# QA Verification Results (to be filled after implementation)
qa_verification:
  reviewer: null
  date: null
  acceptance_criteria: {}
  regression_tests: {}
  notes: []
