# Quality Gate Decision - Story 2.15
# Update Installer for Modules

schema: 1
story: "2.15"
story_title: "Update Installer for Modules"
gate: PASS
status_reason: "Implementation complete. All 6 smoke tests pass. 23 unit tests added."
reviewer: "Dex (Dev)"
updated: "2025-12-01T12:00:00Z"

waiver:
  active: false

# Pre-implementation validation
pre_validation:
  story_format: PASS
  acceptance_criteria: PASS
  definition_of_done: PASS
  dependencies_clear: PASS
  estimates_reasonable: PASS
  rollback_plan: PASS

# Required tests (from story smoke tests INS-01 to INS-06)
required_tests:
  p0_critical:
    - id: INS-01
      name: "Core Created"
      description: "core/ directory exists"
      status: PASS

    - id: INS-02
      name: "Dev Created"
      description: "development/ directory exists"
      status: PASS

    - id: INS-03
      name: "Product Created"
      description: "product/ directory exists"
      status: PASS

    - id: INS-04
      name: "Infra Created"
      description: "infrastructure/ directory exists"
      status: PASS

  p1_important:
    - id: INS-05
      name: "Manifests"
      description: "Manifest files generated"
      status: PASS

    - id: INS-06
      name: "Legacy Mode"
      description: "--legacy creates flat structure"
      status: PASS

# Deliverables scope
deliverables:
  files_to_create:
    - path: "tests/installer/v21-structure.test.js"
      status: DONE
      note: "23 tests for v2.1 structure validation"
  files_to_update:
    - path: "tools/installer/bin/aios.js"
      status: DONE
      note: "Added --legacy flag to CLI"
    - path: "tools/installer/lib/installer.js"
      status: DONE
      note: "Updated v2.1 module paths, expansion pack dependencies"
    - path: "tools/installer/lib/config-loader.js"
      status: DONE
      note: "Updated v2.1 module paths for agents, teams, dependencies"
    - path: "tools/installer/lib/resource-locator.js"
      status: DONE
      note: "Updated v2.1 module paths, module mapping"

  module_structure:
    - name: "Core Module"
      path: ".aios-core/core/"
      contents:
        - "registry/"
        - "quality-gates/"
        - "manifest/"
        - "utils/"
    - name: "Development Module"
      path: ".aios-core/development/"
      contents:
        - "agents/"
        - "tasks/"
        - "templates/"
        - "checklists/"
        - "scripts/"
    - name: "Product Module"
      path: ".aios-core/product/"
      contents:
        - "cli/"
        - "api/"
    - name: "Infrastructure Module"
      path: ".aios-core/infrastructure/"
      contents:
        - "config/"
        - "hooks/"
        - "telemetry/"

# Risk assessment (pre-implementation)
risk_summary:
  totals:
    critical: 0
    high: 1
    medium: 1
    low: 1
  highest: high
  identified_risks:
    - id: "COMPAT-001"
      severity: high
      finding: "New installer may break existing workflows"
      mitigation: "Legacy flag support, thorough testing"
      status: MITIGATED
      resolution: "--legacy flag implemented, 23 tests pass"

    - id: "FILES-001"
      severity: medium
      finding: "File generation paths need updates everywhere"
      mitigation: "Centralized path configuration"
      status: MITIGATED
      resolution: "MODULE_MAPPING constant used across all files"

    - id: "TEMPLATE-001"
      severity: low
      finding: "Templates may have hardcoded paths"
      mitigation: "Audit all templates"
      status: MITIGATED
      resolution: "Templates already use v2.1 paths in source"

  recommendations:
    must_fix: []
    before_start:
      - "Audit all file generation paths"
      - "Test current installer behavior"
      - "Document expected output structure"
    during_implementation:
      - "Update paths in centralized config first"
      - "Test each module directory creation"
      - "Verify legacy mode works"
    before_completion:
      - "All 6 INS tests must pass"
      - "Fresh install creates correct structure"
      - "Legacy mode preserves old behavior"

# Quality scoring (pre-implementation baseline)
quality_score: 93
# Score breakdown:
# - Format compliance: 20/20
# - Acceptance criteria clarity: 19/20
# - Task breakdown: 18/20
# - Risk mitigation: 18/20
# - Documentation: 18/20

# Gate criteria for PASS
pass_criteria:
  - "All P0 tests (INS-01 to INS-04) must pass"
  - "All P1 tests (INS-05 to INS-06) must pass"
  - "Fresh install creates 4-module structure"
  - "All default files in correct locations"
  - "Manifest files generated"
  - "--legacy flag works"

expires: "2025-12-15T00:00:00Z"

evidence:
  story_validated: true
  po_approved: true
  dependencies_met:
    - story: "2.14"
      status: "Done"
      note: "Migration script completed and pushed to main (2025-12-01)"
  file_references_fixed: true
  adr_reference: "ADR-002-migration-map.md"
  blocking_stories:
    - "2.16 (Documentation)"

# CodeRabbit Integration
coderabbit_integration:
  enabled: true
  focus_areas:
    primary:
      - "Directory creation correctness"
      - "File path updates"
      - "Manifest generation"
    secondary:
      - "Legacy mode compatibility"
      - "Template path updates"
  self_healing:
    primary_agent: "@dev"
    max_iterations: 2
    timeout_minutes: 10
    severity_filter:
      - CRITICAL

# QA Verification Results (to be filled after implementation)
qa_verification:
  reviewer: "Quinn (QA)"
  date: "2025-12-01"
  acceptance_criteria:
    AC15.1_core_created: PASS
    AC15.2_dev_created: PASS
    AC15.3_product_created: PASS
    AC15.4_infra_created: PASS
    AC15.5_core_files: PASS
    AC15.6_dev_files: PASS
    AC15.7_product_files: PASS
    AC15.8_infra_files: PASS
    AC15.9_manifests: PASS
    AC15.10_agents_csv: PASS
    AC15.11_workers_csv: PASS
    AC15.12_legacy_flag: PASS
    AC15.13_default_v21: PASS
  regression_tests:
    installer_tests: "81 tests pass (23 new, 58 existing)"
    lint: "PASS (warnings only)"
  notes:
    - "All acceptance criteria verified via tests/installer/v21-structure.test.js"
    - "MODULE_MAPPING constant implemented consistently across all files"
    - "--legacy flag added to CLI, legacyStructure properly passed to installer config"
    - "Manifests directory verified: agents.csv, tasks.csv, workers.csv present"
    - "Pre-existing YAML parsing warnings in 3 agent files (not related to this story)"
    - "Code quality: Clean implementation with proper documentation and caching"

qa_review:
  reviewer: "Quinn (QA)"
  date: "2025-12-01"
  gate_decision: PASS
  summary: |
    Story 2.15 implementation verified. All 81 installer tests pass including 23 new v2.1
    structure tests. All 6 smoke tests (INS-01 to INS-06) verified passing. v2.1 modular
    directory structure correctly implemented in source. MODULE_MAPPING applied consistently
    across resource-locator.js and config-loader.js. --legacy flag properly added to CLI.
  findings:
    - type: "PASS"
      description: "All acceptance criteria met and verified via automated tests"
    - type: "PASS"
      description: "Code quality good - well documented, proper caching, minimal changes"
    - type: "NOTE"
      description: "Pre-existing YAML parsing warnings in aios-master.md, qa.md, ux-design-expert.md - unrelated to this story"
